const APP_CONFIG = {
  NEXT_PUBLIC_MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI as string,
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env
    .NEXT_PUBLIC_FIREBASE_API_KEY as string,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env
    .NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN as string,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_PROJECT_ID as string,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env
    .NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET as string,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID as string,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env
    .NEXT_PUBLIC_FIREBASE_APP_ID as string,
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID as string,
};

export default APP_CONFIG;
