import {
  AlertTriangle,
  ArrowRight,
  Award,
  Briefcase,
  Check,
  ChevronLeft,
  ChevronRight,
  Code,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  GraduationCap,
  HelpCircle,
  Image,
  Kanban,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  ProjectorIcon,
  Settings,
  ShoppingBag,
  Sun,
  Trash2,
  Twitter,
  User,
  UserCircle,
  UserX,
  X,
} from 'lucide-react';

export type Icon = React.ComponentType<React.SVGProps<SVGSVGElement>>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: ShoppingBag,
  spinner: Loader2,
  kanban: Kanban,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash2,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: User,
  user2: UserCircle,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  twitter: Twitter,
  check: Check,
  work: Briefcase,
  education: GraduationCap,
  skills: Code,
  projects: ProjectorIcon,
  awards: Award,
};
